services:
    akeneo_batch.saver.job_instance:
        class: '%akeneo_storage_utils.saver.base.class%'
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%akeneo_batch.entity.job_instance.class%'
